# 01 - Data Cleaning 

This notebook cleans the BreathWatch Air Quality and Health 2015 - 2024 dataset in data/raw/global_air_pollution_dataset.csv to prepare the data for analysis and visualization on isolated variables.

In [30]:
# Setup and imports 

import pandas as pd 
import numpy as np 

pollution_df = pd.read_csv('../data/raw/global_air_pollution_dataset.csv')
pollution_df.describe()

,Year,Month,Latitude,Longitude,Population_Density_per_km2,Green_Cover_Pct,AQI,PM2_5_ugm3,PM10_ugm3,NO2_ugm3,...,Black_Carbon_ugm3,Temperature_C,Humidity_Pct,Wind_Speed_kmh,Atmospheric_Pressure_hPa,Visibility_km,Respiratory_Risk_Index,Cardiovascular_Risk_Index,Cancer_Risk_Index,WHO_PM25_Guideline_ugm3
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,...,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.0
mean,2019.454167,6.495833,8.069055,8.200682,24934.422833,30.511050,166.479833,91.199502,182.133948,114.197563,...,15.253738,14.927967,53.668883,17.650133,999.235533,7.918963,33.295967,27.746517,2.505097,15.0
std,2.856792,3.422660,36.026698,79.400903,14356.426005,16.946146,109.781398,62.392763,129.147072,105.394852,...,8.443542,17.349060,25.153900,10.074917,23.294994,1.372321,21.956280,18.297232,0.951429,0.0
min,2015.000000,1.000000,-54.983900,-129.956600,58.000000,1.000000,1.000000,0.410000,0.760000,0.110000,...,0.500000,-14.900000,10.100000,0.500000,960.000000,3.900000,0.200000,0.200000,0.160000,15.0
25%,2017.000000,4.000000,-22.861000,-60.292525,12268.750000,15.900000,85.750000,45.227500,88.780000,37.200000,...,8.160000,0.000000,32.000000,8.800000,979.000000,7.240000,17.150000,14.275000,1.749000,15.0
50%,2019.000000,7.000000,8.360700,8.873950,24904.000000,30.700000,141.000000,75.665000,147.860000,83.330000,...,15.290000,14.800000,53.300000,17.500000,998.600000,8.240000,28.200000,23.500000,2.490000,15.0
75%,2022.000000,9.000000,39.393525,78.829675,37465.500000,45.100000,221.000000,121.870000,241.172500,156.277500,...,22.492500,30.000000,75.700000,26.500000,1019.300000,8.932500,44.200000,36.800000,3.252000,15.0
max,2024.000000,12.000000,69.959600,144.978400,49995.000000,60.000000,488.000000,339.540000,772.340000,632.400000,...,29.980000,45.000000,98.000000,35.000000,1040.000000,9.990000,97.600000,81.300000,4.950000,15.0

The data is currently orgainzed by RECORD_ID. However, to make patterns and trends more visible, we want to sort the data according to year and season (starting from 2014 all the way to 2024 in the order of winter, spring, summer, fall).

In [31]:
# Sort dataframe by date and season 
season_order = ['Winter', 'Spring', 'Summer', 'Fall']
pollution_df['Date'] = pd.to_datetime (pollution_df['Date'])
pollution_df['Season'] = pd.Categorical(pollution_df['Season'], categories=season_order, ordered=True)
pollution_df.sort_values(by=['Date','Season'], inplace=True)

# Eliminate Record_ID column -> previous sequential ordering
pollution_df.drop(columns=['Record_ID'], inplace=True)

pollution_df.head(20)

,Date,Year,Month,Season,Country,City,Latitude,Longitude,Population_Density_per_km2,Green_Cover_Pct,...,Industry_Nearby,Traffic_Density,Health_Effects,Associated_Diseases,Respiratory_Risk_Index,Cardiovascular_Risk_Index,Cancer_Risk_Index,Daily_Mortality_Risk,Exceeds_WHO_PM25_Standard,WHO_PM25_Guideline_ugm3
669,2015-01-01,2015,1,Winter,South Africa,Pretoria,16.8918,-121.5033,43438,8.8,...,Yes,Medium,Health alert: serious health effects for every...,"Lung Cancer Risk, Heart Attack, Arrhythmia, Pr...",42.6,35.5,0.813,High,Yes,15
2224,2015-01-02,2015,1,Winter,Egypt,Alexandria,40.8396,102.2501,28764,15.5,...,Yes,Very High,Health emergency: everyone is affected; life-t...,"Severe COPD, Heart Failure, Lung Cancer, Neuro...",89.8,74.8,3.441,Very High,Yes,15
2376,2015-01-02,2015,1,Winter,Japan,Fukuoka,10.6877,-96.7981,12478,11.7,...,Yes,Low,No significant health effects,NaN,1.2,1.0,2.549,Low,No,15
4808,2015-01-02,2015,1,Winter,Iran,Tehran,-40.7591,7.5925,22808,20.9,...,Yes,Medium,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",34.4,28.7,1.336,Moderate,Yes,15
427,2015-01-03,2015,1,Winter,South Korea,Daegu,21.9019,97.7119,20332,51.9,...,Yes,Medium,Health alert: serious health effects for every...,"Lung Cancer Risk, Heart Attack, Arrhythmia, Pr...",44.0,36.7,3.272,High,Yes,15
1049,2015-01-03,2015,1,Winter,Australia,Melbourne,-45.5860,67.7402,48352,56.6,...,No,High,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",31.2,26.0,1.739,Moderate,Yes,15
2482,2015-01-03,2015,1,Winter,Canada,Vancouver,-25.4473,-98.9785,9818,55.5,...,Yes,Very High,No significant health effects,NaN,7.6,6.3,3.229,Low,Yes,15
1608,2015-01-04,2015,1,Winter,Nigeria,Abuja,-41.0616,-96.9194,37153,33.3,...,Yes,High,Health alert: serious health effects for every...,"Lung Cancer Risk, Heart Attack, Arrhythmia, Pr...",57.2,47.7,1.450,High,Yes,15
3580,2015-01-04,2015,1,Winter,Indonesia,Surabaya,-18.2454,-85.1048,28572,30.8,...,Yes,Very High,Health alert: serious health effects for every...,"Lung Cancer Risk, Heart Attack, Arrhythmia, Pr...",55.6,46.3,3.533,High,Yes,15
4336,2015-01-04,2015,1,Winter,Colombia,Cali,-39.9956,-101.3267,5209,52.5,...,No,Medium,Unusually sensitive people may experience mino...,Mild asthma exacerbation,13.0,10.8,1.623,Low,Yes,15
5810,2015-01-04,2015,1,Winter,Indonesia,Bandung,38.6379,-53.1964,23766,29.6,...,Yes,Low,Health emergency: everyone is affected; life-t...,"Severe COPD, Heart Failure, Lung Cancer, Neuro...",78.2,65.2,2.303,Very High,Yes,15
55,2015-01-07,2015,1,Winter,Poland,Wroclaw,40.1285,18.8483,10756,8.6,...,No,Low,No significant health effects,NaN,9.4,7.8,1.003,Low,Yes,15
206,2015-01-07,2015,1,Winter,UK,Leeds,56.8832,-88.9863,40746,56.2,...,No,Medium,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",31.0,25.8,3.782,Moderate,Yes,15
5865,2015-01-07,2015,1,Winter,Brazil,Manaus,1.7389,-15.9375,24572,44.1,...,Yes,Very High,Unusually sensitive people may experience mino...,Mild asthma exacerbation,16.8,14.0,3.383,Low,Yes,15
1030,2015-01-09,2015,1,Winter,Ethiopia,Dire Dawa,-50.6436,41.7490,5433,12.7,...,No,Low,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",37.2,31.0,2.493,Moderate,Yes,15
5260,2015-01-09,2015,1,Winter,Poland,Wroclaw,-1.1897,-53.8817,39537,16.1,...,No,Medium,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",31.0,25.8,2.983,Moderate,Yes,15
5569,2015-01-10,2015,1,Winter,Bangladesh,Gazipur,67.9268,20.0433,7109,32.5,...,No,Very High,Health alert: serious health effects for every...,"Lung Cancer Risk, Heart Attack, Arrhythmia, Pr...",50.4,42.0,4.106,High,Yes,15
3385,2015-01-11,2015,1,Winter,Egypt,Giza,-17.4517,-17.4346,25506,20.8,...,Yes,Medium,Everyone may experience health effects; sensit...,"COPD, Ischemic Heart Disease, Stroke Risk, Lun...",32.0,26.7,4.141,Moderate,Yes,15
4965,2015-01-11,2015,1,Winter,France,Marseille,58.4831,99.6168,22501,24.4,...,No,Medium,"Children, elderly, and people with lung/heart ...","Asthma, Bronchitis, Allergic Rhinitis",22.2,18.5,3.825,Moderate,Yes,15
498,2015-01-12,2015,1,Winter,France,Lyon,14.9127,-78.4619,25557,10.3,...,Yes,Very High,No significant health effects,NaN,8.6,7.2,4.111,Low,Yes,15

Now we want to eliminate the NaN row entries to ensure only full completed records remain.

In [36]:
# Check for NaN values across df
print(pollution_df.isna().any())

# Eliminate those rows with empty values 
pollution_df.dropna(inplace=True)
pollution_df.describe()

Date                          False
Year                          False
Month                         False
Season                         True
Country                       False
City                          False
Latitude                      False
Longitude                     False
Population_Density_per_km2    False
Green_Cover_Pct               False
AQI                           False
AQI_Category                  False
Pollution_Alert_Level          True
PM2_5_ugm3                    False
PM10_ugm3                     False
NO2_ugm3                      False
SO2_ugm3                      False
CO_mgm3                       False
O3_ugm3                       False
VOC_ugm3                      False
NH3_ugm3                      False
Lead_Pb_ugm3                  False
Benzene_ugm3                  False
Formaldehyde_ugm3             False
Black_Carbon_ugm3             False
Temperature_C                 False
Humidity_Pct                  False
Wind_Speed_kmh                False
Wind_Direction                False
Atmospheric_Pressure_hPa      False
Visibility_km                 False
Weather_Condition             False
Primary_Pollution_Source      False
Industry_Nearby               False
Traffic_Density               False
Health_Effects                False
Associated_Diseases            True
Respiratory_Risk_Index        False
Cardiovascular_Risk_Index     False
Cancer_Risk_Index             False
Daily_Mortality_Risk          False
Exceeds_WHO_PM25_Standard     False
WHO_PM25_Guideline_ugm3       False
dtype: bool

,Date,Year,Month,Latitude,Longitude,Population_Density_per_km2,Green_Cover_Pct,AQI,PM2_5_ugm3,PM10_ugm3,...,Black_Carbon_ugm3,Temperature_C,Humidity_Pct,Wind_Speed_kmh,Atmospheric_Pressure_hPa,Visibility_km,Respiratory_Risk_Index,Cardiovascular_Risk_Index,Cancer_Risk_Index,WHO_PM25_Guideline_ugm3
count,4047,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,...,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.0
mean,2019-11-06 09:53:30.378057984,2019.446751,5.345441,7.923190,7.943710,24911.360761,30.569039,182.539412,100.009896,199.880904,...,15.280981,14.998023,53.813096,17.624833,999.214727,7.718191,36.507882,30.423128,2.520787,15.0
min,2015-01-01 00:00:00,2015.000000,1.000000,-54.983900,-129.954500,93.000000,1.000000,51.000000,20.510000,35.070000,...,0.500000,-14.900000,10.100000,0.500000,960.000000,3.900000,10.200000,8.500000,0.268000,15.0
25%,2017-05-04 12:00:00,2017.000000,3.000000,-23.093900,-60.024850,12200.500000,16.000000,102.000000,54.590000,107.445000,...,8.235000,0.300000,32.300000,8.800000,979.100000,7.110000,20.400000,17.000000,1.779500,15.0
50%,2019-12-04 00:00:00,2019.000000,5.000000,8.268300,7.371300,24625.000000,30.600000,153.000000,83.420000,164.440000,...,15.350000,14.900000,53.500000,17.400000,998.700000,8.090000,30.600000,25.500000,2.516000,15.0
75%,2022-04-20 00:00:00,2022.000000,7.000000,39.178650,78.155050,37591.500000,45.200000,231.000000,129.195000,259.805000,...,22.590000,30.000000,75.900000,26.500000,1019.200000,8.720000,46.200000,38.500000,3.265500,15.0
max,2024-12-31 00:00:00,2024.000000,12.000000,69.959600,144.978400,49981.000000,60.000000,488.000000,339.540000,772.340000,...,29.980000,45.000000,98.000000,35.000000,1040.000000,9.360000,97.600000,81.300000,4.950000,15.0
std,NaN,2.852888,3.155356,35.993443,78.913591,14372.820122,16.872368,105.123099,60.102284,125.425771,...,8.444796,17.330051,25.146465,10.075621,23.173641,1.314075,21.024620,17.520611,0.941584,0.0

In [37]:
# Load data back into CSV for other notebooks to access
pollution_df.to_csv('../data/clean/cleaned_data.csv', index=False)